### ISSUE TITLE
Launching VLC Player

### ISSUE THREAD

**Issue by vinnybod** [Aloshi/EmulationStation#310]
I've been trying to do this for like an hour now and can't figure it out! I am able to launch vlc through the my command prompt (I'm on windows fyi) and it works just fine doing it like this:

vlc --fullscreen "C:\Users\Emu\\.emulationstation\systems\vlc\NameOfFile.avi" 

I've tried a ton of different combinations in the es_config to get this working and I can get it to launch vlc, but it won't open the video file. This is what I currently have:
	
<command>C:\Users\Emu\\.emulationstation\systems\vlc\vlc.exe --fullscreen "%ROM%"</command>

It will open VLC, but will not open a video file. I noticed when I took away the quotes around ROM and added a space to my filename I got an error in VLC that showed me it was trying to find a video file in "C:\Program Files\...." but shouldn't the %ROM% tag be adding the directory where the files are located into the command? Any advice is appreciated!

**Comment by RealityFork** [comment]
This is a problem for any emulator that does not allow for the wrong separators. I am having the same issue with PCSX2 on windows - it crashes due to the wrong slashes being used.

A fix would be greatly appreciated.

**Comment by RealityFork** [comment]
Since I am extremely impatient I've made a workaround for this situation:
Create a bat file with the following contents (I called mine convert.bat):

`set a=%1
set a=%a:/=\%
START C:\EmulationStation\PCSX2\pcsx2-r5875.exe %a%`

Obviously you need to change the last line to reflect whatever emulator you want to start.
Then change the `<command>` line in your systems config to look like this:
`<command>C:\EmulationStation\convert.bat "%ROM_RAW%"</command>`

Again, change the path to the actual path to your batch file.
The batch file replaces all instances of '/' with '\', and this has got PCSX2 working for me.

Hope it helps!

**Comment by Aloshi** [comment]
I've finally some changes to how ES handles paths on Windows. `%ROM%` and `%ROM_RAW%` now use the platform's native directory separator (i.e. backslashes on Windows, forward slashes on everything else). `%ROM%` is also now properly escaped on Windows (enclosed in quotes, instead of escaped with backslashes). While I was at it, I made non-ASCII paths work on Windows as well. That should resolve this issue. Sorry it took me so long to do.

See commits 1500edbde3039863437851799f3a581e20c496d7 and df896cb933882219572b4639cd2347ecf45fd102 for details.
