### ISSUE TITLE
EmulationStation using 25% CPU on idle

### ISSUE THREAD

**Issue by adrianmoisey** [Aloshi/EmulationStation#43]
EmulationStation uses about 25% CPU on a Raspberry Pi on idle.
If possible it should use less
![Screen shot 2013-01-14 at 1 29 55 PM](https://f.cloud.github.com/assets/736329/64310/e59f262a-5e3d-11e2-9e12-42162b409eb9.png)

**Comment by tommitytom** [comment]
Sorry to dig up an old issue, but has there been a regression here?  When the screen is dimmed due to be idle, or by enabling the screensaver with 'select' (on a Pi 3 B+), emulationstation is using around 17% CPU.  It's part of a retropie build so not sure if that factors in to it at all.  I don't have any games to test at the moment, but when I load Kodi emulationstation CPU load backs right off
