### ISSUE TITLE
Gamepad not detected if taken out and re-inserted while emulationstation is loaded

### ISSUE THREAD

**Issue by adrianmoisey** [Aloshi/EmulationStation#46]
If I load ES with a gamepad plugged in, the gamepad works. If I remove and reinsert the gamepad then ES doesn't detect it. Is it possible to make it scan for new gamepads on some interval (every 15 seconds?) while in the menu?

**Comment by trinitronx** [comment]
I hate to chime in on a closed thread that looks like it has a solution.  However, because this is coming up as a top search result in Google, I think it's important for future Googlers on this topic to know:

With more recent versions of SDL 2.0, there are now [events for joystick add & remove](https://wiki.libsdl.org/SDL_EventType) supported.  This [StackOverfow answer helps explain](https://gamedev.stackexchange.com/a/73544) how they work.
