### ISSUE TITLE
Feature request: dim screen

### ISSUE THREAD

**Issue by adrianmoisey** [Aloshi/EmulationStation#48]
Hi

Just a feature request, close if you don't like it or think it's unrealistic.
I'd like EmulationStation to dim the entire screen after x seconds of being idle. Not sure on the number, but may be 60 seconds.

**Comment by robertomurta** [comment]
Hi Aloshi.
I don't know if is too long for a possible reopening of the issue, or another issue, been using emulationstation for a week, on a macbook pro (intel core2) with debian and notice the 4% of cpu usage when idle (blank or dim), and CPU clock speed is at max all the time (it get hot and fan at max). It's been a issue since I also use as personal server, and want to use emulationstation as main interface.
I think the problem is the cpu speed that is not allowed to step down, it would be really nice a lower cpufreq for quieter server when not in use.
