### ISSUE TITLE
how do you change the resolution of emulation station?

### ISSUE THREAD

**Issue by Ololziver** [Aloshi/EmulationStation#55]
I'm trying to use "sudo emulationstation -w 720 -h 336" to change the resolution but cant for the life of me do it, I've tried changing the settings in retroarch.cfg and that has no change at all either, have you got any ideas? it needs to be that size to fit the screen of a project at university.

Thankyou in advance!

**Comment by maestroni** [comment]
I have a similar request as the one above but can't seem to figure it out because file /usr/bin/emulationstation has changed since 2013. 
 
I am running emulationstation on my raspberry pi and am having trouble with a very specific resolution setting.  I have a HDTV mounted in an arcade cabinet in portrait mode like attached in the pictures and would like to trim down the aspect rato to be a 4:3 format, and maybe change some overscan settings to move the display up a little.   I do have the config.txt file changed games play with a modified resolution and overscan settings, just not my emulationstation menu.
![img_1881](https://user-images.githubusercontent.com/32663840/31371208-83c70ba6-ad44-11e7-9827-b48c81ec4b32.JPG)
![img_1882](https://user-images.githubusercontent.com/32663840/31371209-83e2d520-ad44-11e7-80f8-28263c55cafe.JPG)
![img_1875](https://user-images.githubusercontent.com/32663840/31371215-8bcc2dd6-ad44-11e7-9142-94755912ef11.JPG)

Thanks in advance.
