### ISSUE TITLE
Already mapped!

### ISSUE THREAD

**Issue by logicpi** [Aloshi/EmulationStation#67]
Good evening,  I'm new to the world of Pi, but I've found this EmulationStation relatively quickly.  I've successfully loaded NES roms!  I've got a RetroLink NES (http://inadawords.com/cool-stuff/retrolink-usb-nes-controller-review) controller which the emulation software recognizes.  My issue is that I'm lost as you how to override the button assignments, or if it's even possible.  The NES controller has 9 inputs (rock "d" pad, A, B, select, and start), so, the 9th input, "PageUp" cannot be assigned.  And, since I am in the process of assigning to the controller, the keyboard doesn't appear to be responsive.  

My thinking is to assign through the keyboard, and then modify the es_input.cfg file for the USB controller later.  Will this work?  Is there a simpler way I'm overlooking?

Thanks much,

-Jared

**Comment by DJDiggety** [comment]
Using Emulation Station, is it possible to assign more than one input command to a particular joystick button, instead of it saying "Already Taken"?  For example, I can't get the N64 emulator in Retropie to work with my arcade joystick because the joystick is assigned to D-Pad controls (Up,Down,Left,Right).. and the N64 is looking for the Analog Joystick controls instead of the D-Pad. It would be fixed if I could assign both commands to the one joystick... Is it possible to configure both of the Inputs to work with the one joystick, so it is simultaneously controlling both?  Thank you so much for your help!
